package com.tonelope.tennischarter.model;

public enum StrokeType {
	FOREHAND,
	FOREHAND_LOB,
	FOREHAND_SLICE,
	FOREHAND_DROPSHOT,
	FOREHAND_VOLLEY,
	BACKHAND,
	BACKHAND_LOB,
	BACKHAND_DROPSHOT,
	BACKHAND_SLICE,
	BACKHAND_VOLLEY,
	OVERHEAD,
	BACKHAND_OVERHEAD,
	FIRST_SERVE,
	SECOND_SERVE,
	OTHER
}
